name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: show files
      run: |
        ls ${{ github.workspace }}
    - name: Set up a Vertica server
      timeout-minutes: 15
      run: |
        docker run -d -p 5433:5433 -p 5444:5444 \
          -v ${{ github.workspace }}:/home/dbadmin/odbc-loader \
          --name vertica_docker \
          vertica/vertica-ce:12.0.2-0
        echo "Vertica startup ..."
        until docker exec vertica_docker test -f /data/vertica/VMart/agent_start.out; do \
          echo "..."; \
          sleep 3; \
        done;
        echo "Vertica is up"
        docker exec -u dbadmin vertica_docker /opt/vertica/bin/vsql -c "\l"
        docker exec -u dbadmin vertica_docker /opt/vertica/bin/vsql -c "select version()"
    - name: Build & Install UDx
      run: |
        docker exec -u dbadmin vertica_docker ls /var/odbc-loader
        docker exec -u root vertica_docker yum -y install centos-release-scl
        docker exec -u root vertica_docker yum -y install devtoolset-7
        docker exec -u dbadmin vertica_docker scl enable devtoolset-7 bash && \
        cd /home/dbadmin/odbc-loader && \
        make TARGET=/home/dbadmin/build && \
        make install TARGET=/home/dbadmin/build